### ISSUE TITLE
EDDI server stopped automatically after few hours don't use

### ISSUE THREAD

**Issue by dgks0n** [labsai/EDDI#112]
I deployed EDDI server on Centos7, after few hours it stopped automatically. I checked the log and below is last line of log:

`Pool did not terminate`

And I guess it related to below method:

```
private void initExecutorServiceShutdownHook() {
        Runtime.getRuntime().addShutdownHook(new Thread("ShutdownHook_ExecutorService") {
            @Override
            public void run() {
                executorService.shutdown(); // Disable new tasks from being submitted
                try {
                    // Wait a while for existing tasks to terminate
                    if (!executorService.awaitTermination(60, TimeUnit.SECONDS)) {
                        executorService.shutdownNow(); // Cancel currently executing tasks
                        // Wait a while for tasks to respond to being cancelled
                        if (!executorService.awaitTermination(60, TimeUnit.SECONDS)) {
                            log.error("Pool did not terminate");
                        }
                    }
                } catch (InterruptedException e) {
                    // (Re-)Cancel if current thread also interrupted
                    executorService.shutdownNow();
                    // Preserve interrupt status
                    Thread.currentThread().interrupt();
                    log.error(e.getLocalizedMessage(), e);
                }
            }
        });
    }
```

Is there any suggestion?

**Comment by ginccc** [comment]
Well, if this code part had been executed, then it means the JVM received a shutdown signal from OS.
I recommend running EDDI inside docker container instead of on an OS directly as it has been tested and optimized for use as Docker.

**Comment by dgks0n** [comment]
Hi ginccc, Is it requires to register shutdown a hook?

**Comment by ginccc** [comment]
if you want a clean shutdown - with all releasing of resources happening - then yes, you will need it.

But again, the only reason this code will be executed is because your OS send it a termination signal SIGTERM

**Comment by dgks0n** [comment]
In fact, I got apiserver-4.4-package.zip after run

```
mvn clean install
```
then upload it to my clean server (it's empty except JAVA and MySQL). After unzip package I executed bash with below command line:

```
./ApiServerStartup.sh production
```

That's all, I hope it work as well but you know it stopped automatically after few hours as main reason is OS send it a termination signal SIGTERM while I did nothing. 

In reality I don't want to download source codes to my CentOS server. Can you give me some ideas to solve it?

**Comment by ginccc** [comment]
use docker!

https://hub.docker.com/r/labsai/eddi/ 
use eddi version 4.3

of course you also need to spin up a mongodb as docker then. If you use mysql in addition, I'd recommend to you to host this db as docker container as well.

**Comment by ginccc** [comment]
please note, 4.4 is still in dev, thus not production ready yet. use v4.3
