### ISSUE TITLE
Please add a web live chat example or tutorial

### ISSUE THREAD

**Issue by mariusa** [labsai/EDDI#114]
Please add a web live chat example or tutorial. Thanks!

These might help for UI:
https://github.com/mattmezza/vue-beautiful-chat
https://github.com/Coffcer/vue-chat

**Comment by ginccc** [comment]
there is a web chat for testing available: http://localhost:7070/chat/<environment>/<botId>

docs with tutorials are here: http://docs.labs.ai

your version of a chat window looks good, how about you implement it and contribute to the project?
