### ISSUE TITLE
Bot IDs in Example Bots do not match IDs returned from REST API

### ISSUE THREAD

**Issue by donasumu** [labsai/EDDI#262]
Bot IDs listed in the descriptors of the examples provided do not match the Bot IDs returned from   
**http://localhost:7070/deploymentstore/deployments**
which are listed below:
[
  {
    "botId": "608c7fe220afe1725141d87c",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608c7fe320afe1725141d884",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608c7fe320afe1725141d891",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608c7fe320afe1725141d897",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608c7fe320afe1725141d8a1",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608c7fe420afe1725141d8b2",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608c7fe420afe1725141d8b9",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608c7fe420afe1725141d8c1",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecae7efa5af1a1d00b74f",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecae7efa5af1a1d00b757",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecae8efa5af1a1d00b764",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecae8efa5af1a1d00b76a",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecae8efa5af1a1d00b774",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecae8efa5af1a1d00b785",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecae8efa5af1a1d00b78c",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecae9efa5af1a1d00b794",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecaeeefa5af1a1d00b79a",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecaeeefa5af1a1d00b7a2",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecaefefa5af1a1d00b7af",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecaefefa5af1a1d00b7b5",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecaefefa5af1a1d00b7bf",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecaefefa5af1a1d00b7d0",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecaefefa5af1a1d00b7d7",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  },
  {
    "botId": "608ecaefefa5af1a1d00b7df",
    "botVersion": 1,
    "environment": "unrestricted",
    "deploymentStatus": "deployed"
  }
]

**Comment by ginccc** [comment]
Hi @donasumu!
Sorry for the late reply, somehow missed this..

bot IDs are different on every import to avoid duplication issues. Meaning, whenever you launch a new eddi instance and import any bot like the examples, they will have different IDs as each of the config resource is newly being created within your eddi instance.
