### ISSUE TITLE
How to use external rest resources

### ISSUE THREAD

**Issue by Malvelun** [labsai/EDDI#81]
Hi Gregor,

I would like to use information from an external rest service (in JSON format) as part of an answer to a user's question to a chatbot. How can this be achieved? Do I have to write a Java plugin or is it possible to only create actions / outputs over the rest interface that use third party services somehow?

Thank you in advance!

**Comment by ginccc** [comment]
The most flexible way is the (undocumented) callback task plugin, which sends the entire conversation memory as json to another external rest service and receives back an update conversationMemory (such as data other services) This plugin is used similar like the parser, behavior or output ("eddi://ai.labs.callback").
the config is callbackUri & timeoutInMillis
callbackUri should be a service that receives a json based on this model (https://github.com/labsai/EDDI/blob/master/conversationmemory-definition/src/main/java/ai/labs/memory/model/ConversationMemorySnapshot.java), alter it or populate it with all kinds of data and send the update conversationMemory back as response so eddi can merge it with its internal memory.
 
If you want to do java programming within eddi, you would have three more plugin endpoints (ai.labs.parser.model.IDictionary, ai.labs.parser.correction.ICorrection, ai.labs.behavior.impl.extensions.IBehaviorExtension).

Hope this helps. Update to the docs is coming soon..
