### ISSUE TITLE
Bot status in In Progress for more than 1 our

### ISSUE THREAD

**Issue by ionchik9** [labsai/EDDI#82]
Hello guys!
I've started all the services and posted Json configs as mentioned 
https://labsai.atlassian.net/wiki/spaces/EDDI/pages/168410/Creating+a+Chatbot

But administration/unrestricted/deploymentstatus/XXX gives me IN_PROGRESS and
/chat/unrestricted/ -- "Bot is still warming"

I haven't found any exceptions in logs at the moment is it OK that it takes so long?

**Comment by ginccc** [comment]
No, there is highly likely a config error. Bot deployment only takes a few hundred milliseconds.. only with huge conversation flows it might take a second or two... 

If I have to make an educated guess than I would say you have forgotten to replace the IDs and Version info in the package or bot config
such as <UNIQUE_DICTIONARY_ID>?version=<DICTIONARY_VERSION>
You have to replace them with the IDs and Version you will get back when creating the dictionaries, behavior and so on.. This way you loosely couple these configs together.
