### ISSUE TITLE
Any plans to support PostgreSQL ?

### ISSUE THREAD

**Issue by khhwang838** [labsai/EDDI#95]
Hi, I'm trying to use EDDI, and I'm wondering if you guys planning to support any other databases.

I want to use PostgreSQL instead of MongoDB.

So, I want to know if there's a way to do that.

Thank you.

**Comment by ginccc** [comment]
It is not on the roadmap for now, no. Would be a rather bigger task to accomplish.

Nonetheless, using a SQL db in addition in which to store data that can be integrated in eddi is a quite common use case.
